### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by Btodhunter** [Btodhunter/test-ci#1]
```
details:
  msg: It is better to keep your mouth closed and let people think you are a fool than to open it and remove all doubt - Mark Twain
id: b46370d45ff44516a4aa44b18e2cf33e
level: info
message: Unsolicited random wisdom of the moment
resource:
  id: null
  type: wisdom
  user_id: admin
source:
  base_url: http://anchore-anchore-engine-enterprise-notifications:8668
  hostid: anchore-anchore-engine-api-c94f7ff96-nlcpg
  request_id: null
  servicename: notifications
timestamp: '2019-12-12T19:10:58.910515'
type: system.test.random_wisdom
```
