### ISSUE TITLE
[ANCHORE] Service down

### ISSUE THREAD

**Issue by Btodhunter** [Btodhunter/test-ci#10]
```
details:
  cause: no heartbeat from service in (300) seconds
  host_id: anchore-anchore-engine-analyzer-5d57c859b4-8xrwz
  service_name: analyzer
id: b002bb9889364296b974dd06d6b2ada7
level: error
message: Service down
resource:
  id: http://anchore-anchore-engine-analyzer:8084
  type: service
  user_id: admin
source:
  base_url: http://anchore-anchore-engine-catalog:8082
  hostid: anchore-anchore-engine-catalog-8d5d54cc7-x7744
  request_id: null
  servicename: catalog
timestamp: '2019-12-12T23:34:50.018968Z'
type: system.service.state_transition.down
```
