### ISSUE TITLE
[ANCHORE] Feeds sync task started

### ISSUE THREAD

**Issue by Btodhunter** [Btodhunter/test-ci#11]
```
details:
  sync_feed_types:
  - vulnerabilities
  - nvdv2
  - vulndb
id: 7f8e360ff1d84dd9be1e8e6065c99412
level: info
message: Feeds sync task started
resource:
  id: null
  type: feeds
  user_id: admin
source:
  base_url: http://anchore-anchore-engine-policy:8087
  hostid: anchore-anchore-engine-policy-689dcfcf45-h7rx9
  request_id: null
  servicename: policy_engine
timestamp: '2019-12-12T23:34:50.380750Z'
type: system.feeds.sync.started
```
