### ISSUE TITLE
[ANCHORE] Feed sync started

### ISSUE THREAD

**Issue by Btodhunter** [Btodhunter/test-ci#12]
```
details: {}
id: 03aeff8dfbd745348172c8dbbe8dd700
level: info
message: Feed sync started
resource:
  id: vulnerabilities
  type: feed
  user_id: admin
source:
  base_url: http://anchore-anchore-engine-policy:8087
  hostid: anchore-anchore-engine-policy-689dcfcf45-h7rx9
  request_id: null
  servicename: policy_engine
timestamp: '2019-12-12T23:34:53.611266Z'
type: system.feeds.sync.feed_started
```
