### ISSUE TITLE
[ANCHORE] Feed sync failed

### ISSUE THREAD

**Issue by Btodhunter** [Btodhunter/test-ci#13]
```
details:
  cause: 'Feed list operation failed. Msg: None. Response: server error: HTTPConnectionPool(host=''anchore-anchore-engine-enterprise-feeds'', port=8448): Max retries exceeded with url: /v1/feeds (Caused by NewConnectionError(''<urllib3.connection.HTTPConnection object at 0x7f6faf591e10>: Failed to establish a new connection: [Errno 111] Connection refused'',))'
id: c439c509f1a843528eac22a263427d19
level: error
message: Feed sync failed
resource:
  id: vulnerabilities
  type: feed
  user_id: admin
source:
  base_url: http://anchore-anchore-engine-policy:8087
  hostid: anchore-anchore-engine-policy-689dcfcf45-h7rx9
  request_id: null
  servicename: policy_engine
timestamp: '2019-12-12T23:34:53.717363Z'
type: system.feeds.sync.feed_failed
```
