### ISSUE TITLE
[ANCHORE] Feed sync started

### ISSUE THREAD

**Issue by Btodhunter** [Btodhunter/test-ci#14]
```
details: {}
id: 014e45924f2f4b3ba7c6439008160f2e
level: info
message: Feed sync started
resource:
  id: nvdv2
  type: feed
  user_id: admin
source:
  base_url: http://anchore-anchore-engine-policy:8087
  hostid: anchore-anchore-engine-policy-689dcfcf45-h7rx9
  request_id: null
  servicename: policy_engine
timestamp: '2019-12-12T23:34:56.875108Z'
type: system.feeds.sync.feed_started
```
