### ISSUE TITLE
[ANCHORE] Feed sync started

### ISSUE THREAD

**Issue by Btodhunter** [Btodhunter/test-ci#16]
```
details: {}
id: bbef2c0a8f1e4902898f518d503a963c
level: info
message: Feed sync started
resource:
  id: vulndb
  type: feed
  user_id: admin
source:
  base_url: http://anchore-anchore-engine-policy:8087
  hostid: anchore-anchore-engine-policy-689dcfcf45-h7rx9
  request_id: null
  servicename: policy_engine
timestamp: '2019-12-12T23:35:00.139188Z'
type: system.feeds.sync.feed_started
```
