### ISSUE TITLE
[ANCHORE] Feeds sync task completed

### ISSUE THREAD

**Issue by Btodhunter** [Btodhunter/test-ci#18]
```
details:
  sync_feed_types:
  - vulnerabilities
  - nvdv2
  - vulndb
id: e4a4c544730a4513b57690f9b9671363
level: info
message: Feeds sync task completed
resource:
  id: null
  type: feeds
  user_id: admin
source:
  base_url: http://anchore-anchore-engine-policy:8087
  hostid: anchore-anchore-engine-policy-689dcfcf45-h7rx9
  request_id: null
  servicename: policy_engine
timestamp: '2019-12-12T23:35:00.264538Z'
type: system.feeds.sync.completed
```
