### ISSUE TITLE
[ANCHORE] Service orphaned

### ISSUE THREAD

**Issue by Btodhunter** [Btodhunter/test-ci#19]
```
details:
  cause: no heartbeat from service in (3600) seconds
  host_id: anchore-anchore-engine-analyzer-5d57c859b4-8xrwz
  service_name: analyzer
id: 922bf3ddac9a46feb40149166b3334f9
level: error
message: Service orphaned
resource:
  id: http://anchore-anchore-engine-analyzer:8084
  type: service
  user_id: admin
source:
  base_url: http://anchore-anchore-engine-catalog:8082
  hostid: anchore-anchore-engine-catalog-8d5d54cc7-x7744
  request_id: null
  servicename: catalog
timestamp: '2019-12-12T23:35:05.173848Z'
type: system.service.state_transition.orphaned
```
