### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by Btodhunter** [Btodhunter/test-ci#2]
```
details:
  msg: The very ink with which history is written is merely fluid prejudice - Mark Twain
id: 82fe43043066448db04277a644fb064b
level: info
message: Unsolicited random wisdom of the moment
resource:
  id: null
  type: wisdom
  user_id: admin
source:
  base_url: http://anchore-anchore-engine-enterprise-notifications:8668
  hostid: anchore-anchore-engine-api-c94f7ff96-nlcpg
  request_id: null
  servicename: notifications
timestamp: '2019-12-12T19:11:39.222991'
type: system.test.random_wisdom
```
