### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by Btodhunter** [Btodhunter/test-ci#3]
```
details:
  msg: It is better to keep your mouth closed and let people think you are a fool than to open it and remove all doubt - Mark Twain
id: ce280e0618a842558a028fc0c878e41c
level: info
message: Unsolicited random wisdom of the moment
resource:
  id: null
  type: wisdom
  user_id: admin
source:
  base_url: http://anchore-anchore-engine-enterprise-notifications:8668
  hostid: anchore-anchore-engine-api-c94f7ff96-nlcpg
  request_id: null
  servicename: notifications
timestamp: '2019-12-12T19:12:04.643027'
type: system.test.random_wisdom
```
