### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by Btodhunter** [Btodhunter/test-ci#4]
```
details:
  msg: The true sign of intelligence is not knowledge but imagination - Albert Einstein
id: 0fe6c65ba90d4c54b5039834c0b4a938
level: info
message: Unsolicited random wisdom of the moment
resource:
  id: null
  type: wisdom
  user_id: admin
source:
  base_url: http://anchore-anchore-engine-enterprise-notifications:8668
  hostid: anchore-anchore-engine-api-84b4d98848-9mncd
  request_id: null
  servicename: notifications
timestamp: '2019-12-12T19:16:52.504968'
type: system.test.random_wisdom
```
