### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by Btodhunter** [Btodhunter/test-ci#5]
```
details:
  msg: Never give a sword to a man who can't dance - Confucius
id: 9bc789f21c704a73945e01942c91d3ae
level: info
message: Unsolicited random wisdom of the moment
resource:
  id: null
  type: wisdom
  user_id: admin
source:
  base_url: http://anchore-anchore-engine-enterprise-notifications:8668
  hostid: anchore-anchore-engine-api-84b4d98848-9mncd
  request_id: null
  servicename: notifications
timestamp: '2019-12-12T19:18:26.153008'
type: system.test.random_wisdom
```
