### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by Btodhunter** [Btodhunter/test-ci#6]
```
details:
  msg: Moderation is a fatal thing. Nothing succeeds like excess - Oscar Wilde
id: 9db803ea90e2464c9666515ff19159df
level: info
message: Unsolicited random wisdom of the moment
resource:
  id: null
  type: wisdom
  user_id: admin
source:
  base_url: http://anchore-anchore-engine-enterprise-notifications:8668
  hostid: anchore-anchore-engine-api-84b4d98848-9mncd
  request_id: null
  servicename: notifications
timestamp: '2019-12-12T19:46:44.809312'
type: system.test.random_wisdom
```
