### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by Btodhunter** [Btodhunter/test-ci#7]
```
details:
  msg: Never pick a fight with people who buy ink by the barrel - Mark Twain
id: a721c9089dab4102b4c8842d8d96555d
level: info
message: Unsolicited random wisdom of the moment
resource:
  id: null
  type: wisdom
  user_id: admin
source:
  base_url: http://anchore-anchore-engine-enterprise-notifications:8668
  hostid: anchore-anchore-engine-api-84b4d98848-9mncd
  request_id: null
  servicename: notifications
timestamp: '2019-12-12T19:46:58.220007'
type: system.test.random_wisdom
```
