### ISSUE TITLE
[ANCHORE] Configured authz plugin failing health check

### ISSUE THREAD

**Issue by Btodhunter** [Btodhunter/test-ci#8]
```
details:
  cause: Internal authz check returned False, External authz check returned True
  host_id: anchore-anchore-engine-api-84b4d98848-9mncd
  plugin: ExternalAuthorizationHandler
  service_name: apiext
id: 42e65f296d8b453b8672ad40da735418
level: error
message: Configured authz plugin failing health check
resource:
  id: null
  type: service
  user_id: admin
source:
  base_url: http://anchore-anchore-engine-api:8228
  hostid: anchore-anchore-engine-api-84b4d98848-9mncd
  request_id: null
  servicename: apiext
timestamp: '2019-12-12T19:59:02.525944Z'
type: system.service.authz_plugin_healthcheck_failed
```
