### ISSUE TITLE
[ANCHORE] Service orphaned

### ISSUE THREAD

**Issue by Btodhunter** [Btodhunter/test-ci#9]
```
details:
  cause: no heartbeat from service in (3600) seconds
  host_id: anchore-anchore-engine-simplequeue-7f5764b997-jqg49
  service_name: simplequeue
id: 3482701540ba43cc81894e4ca51db2e6
level: error
message: Service orphaned
resource:
  id: http://anchore-anchore-engine-simplequeue:8083
  type: service
  user_id: admin
source:
  base_url: http://anchore-anchore-engine-catalog:8082
  hostid: anchore-anchore-engine-catalog-8d5d54cc7-x7744
  request_id: null
  servicename: catalog
timestamp: '2019-12-12T23:34:49.391800Z'
type: system.service.state_transition.orphaned
```
